#!/bin/sh
rmmod pcspkr
echo 64 > /sys/class/backlight/amdgpu_bl0/brightness
mkfs.vfat -F 32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
mkfs.f2fs -f /dev/nvme0n1p3
mount /dev/nvme0n1p3 /mnt
mkdir /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot
echo 'Server = https://mirror.arizona.edu/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
pacman -Sy && pacman -S archlinux-keyring
pacstrap -i /mnt base base-devel eog epiphany evince fish gdm git gnome-builder gnome-calculator gnome-control-center gnome-shell gst-plugin-pipewire gst-plugin-va gst-plugins-ugly libva-mesa-driver linux linux-firmware nautilus network-manager-applet power-profiles-daemon
printf "/dev/nvme0n1p1\t/boot\tvfat\tnoatime\t0\t2\n/dev/nvme0n1p2\tnone\tswap\tsw\t0\t0\n/dev/nvme0n1p3\t/\tf2fs\tnoatime\t0\t1" > /mnt/etc/fstab
echo "en_US.UTF-8 UTF-8" > /mnt/etc/locale.gen
echo LANG=en_US.UTF-8 > /mnt/etc/locale.conf
echo "blacklist pcspkr" > /mnt/etc/modprobe.d/blacklist.conf
echo arch > /mnt/etc/hostname
echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >> /mnt/etc/sudoers
echo "exec fish" >> /mnt/etc/bash.bashrc
printf 'export XDG_CACHE_HOME=$HOME/.cache\nexport XDG_CONFIG_HOME=$HOME/.config\nexport XDG_DATA_HOME=$HOME/.local/share\nexport XDG_STATE_HOME=$HOME/.local/state\nexport GNUPGHOME=$XDG_DATA_HOME/gnupg' > /mnt/etc/profile.d/xdg.sh
cat <<EOF > /mnt/root/part2.sh
ln -sf /usr/share/zoneinfo/US/Arizona /etc/localtime
hwclock --systohc
locale-gen
useradd -c "Neel Jepaliya" -m -G wheel -s /bin/bash neel
passwd neel
passwd
systemctl enable gdm NetworkManager
bootctl install
rm /boot/initramfs-linux-fallback.img
mv /boot/initramfs-linux.img /boot/initrd
mv /boot/vmlinuz-linux /boot/linux
printf "default arch.conf\ntimeout 4\neditor no\nconsole-mode max" > /boot/loader/loader.conf
printf "title arch\nlinux /linux\ninitrd /initrd\noptions root=/dev/nvme0n1p3 resume=/dev/nvme0n1p2 rw quiet" > /boot/loader/entries/arch.conf
su - neel -c "git clone https://aur.archlinux.org/libpamac-aur.git; cd libpamac-aur; makepkg -si --noconfirm --asdeps"
su - neel -c "git clone https://aur.archlinux.org/pamac-aur.git; cd pamac-aur; makepkg -si --noconfirm"
su - neel -c "git clone https://aur.archlinux.org/adw-gtk3.git; cd adw-gtk3; makepkg -si --noconfirm"
su - neel -c "git clone https://aur.archlinux.org/gnome-console.git; cd gnome-console; makepkg -si --noconfirm"
su - neel -c "git clone https://aur.archlinux.org/extension-manager.git; cd extension-manager; makepkg -si --noconfirm"
su - neel -c "rm -rf ~/.*; rm -rf ~/*"
su - neel -c "mkdir ~/{audio,document,download,photo,video}"
su - neel -c "mkdir ~/.config"
su - neel -c "gsettings set org.gnome.desktop.interface clock-show-date false"
su - neel -c "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"
su - neel -c "gsettings set org.gnome.desktop.interface document-font-name 'Noto Serif 12'"
su - neel -c "gsettings set org.gnome.desktop.interface enable-hot-corners false"
su - neel -c "gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'"
su - neel -c "gsettings set org.gnome.desktop.interface font-name 'Noto Sans 12'"
su - neel -c "gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'"
su - neel -c "gsettings set org.gnome.desktop.interface monospace-font-name 'Noto Sans Mono 12'"
su - neel -c "gsettings set org.gnome.nautilus.preferences show-hidden-files true"
su - neel -c "gsettings set org.gtk.Settings.FileChooser show-hidden true"
su - neel -c "gsettings set org.gtk.gtk4.Settings.FileChooser show-hidden true"
su - neel -c "gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 16"
su - neel -c "gsettings set org.gnome.desktop.peripherals.keyboard delay 256"
su - neel -c "gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true"
su - neel -c "gsettings set org.gnome.mutter auto-maximize false"
su - neel -c "gsettings set org.gnome.shell had-bluetooth-devices-setup true"
su - neel -c "printf 'XDG_DOCUMENTS_DIR="$HOME/document"\nXDG_DOWNLOAD_DIR="$HOME/download"\nXDG_MUSIC_DIR="$HOME/audio"\nXDG_PICTURES_DIR="$HOME/photo"\nXDG_VIDEOS_DIR="$HOME/video"' > /mnt/home/neel/.config/user-dirs.dirs"
su - neel -c "mkdir -p ~/.local/share/gnupg"
su - neel -c "mkdir -p ~/.local/share/themes/Custom/gnome-shell"
su - neel -c "printf '#panelBox {\n\tbackground: transparent;\n\tpadding-top: 6px;\n\tpadding-right: 6px;\n\tpadding-left: 6px;\n}\n#panel {\n\tbackground: #303030;\n\tborder-radius: 12px;\n}' > ~/.local/share/themes/Custom/gnome-shell/gnome-shell.css"
exit
EOF
chmod +x /mnt/root/part2.sh
arch-chroot /mnt /root/part2.sh
rm -rf /mnt/root/.*
rm -rf /mnt/root/part2.sh
umount -R /mnt
